image: samueldebruyn/debian-git

pipelines:
  branches:
    staging:
    - step:
        script:
          - apt-get update
          - apt-get -qq install git-ftp
          - git ftp push -vv --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://$FTP_HOST/$STAGING_FTP_PATH